#!/bin/bash

# Detect monitors
if command -v hyprctl &> /dev/null; then
  # Try getting monitors from hyprctl if available
  monitors=$(hyprctl monitors all -j | jq -r '.[].name' | sort -u)
else
  # Fallback to sysfs (card0 usually)
  # Look for connected monitors in /sys/class/drm
  # This is a rough heuristic
  monitors=$(find /sys/class/drm -name "card*-*" | grep -v "\-TTM" | sed 's/.*card[0-9]*-\(.*\)/\1/' | sort -u)
fi

if [ -z "$monitors" ]; then
  echo "No monitors detected."
  exit 0
fi

echo "Detected monitors:"
echo "$monitors"

# Select monitors to enable
echo "Select monitors to ENABLE (Space to select, Enter to confirm):"
# gum choose --no-limit allows selecting multiple.
enabled_monitors=$(echo "$monitors" | gum choose --no-limit --header "Select monitors to ENABLE")

if [ -z "$enabled_monitors" ]; then
  echo "No monitors selected. Skipping monitor configuration."
  exit 0
fi

# Determine primary monitor
monitor_count=$(echo "$enabled_monitors" | wc -l)
primary_monitor=""

if [ "$monitor_count" -gt 1 ]; then
  echo "Select PRIMARY monitor:"
  primary_monitor=$(echo "$enabled_monitors" | gum choose --header "Select PRIMARY monitor")
else
  primary_monitor="$enabled_monitors"
fi

echo "Primary monitor: $primary_monitor"

# Generate config content
config_file="$HOME/.config/hypr/monitors.conf"
env_file="$HOME/.config/environment.d/monitors.conf"

{
  echo "# Generated by Omarchy installer"
  echo "# See https://wiki.hyprland.org/Configuring/Monitors/"
  echo 
  echo "# Default scale for high-DPI (adjust as needed)"
  echo "env = GDK_SCALE,2"
  echo
} > "$config_file"

# Iterate over all detected monitors to configure them
# We enable selected ones and verify if we need to explicitly disable others (optional, Hyprland usually ignores disconnected)
# But here we only care about configuring the ones we know about.

for mon in $enabled_monitors; do
  # Default config: auto resolution, auto position, auto scale
  # We can try to be smart about positioning if we had EDID info, but for now just 'auto'
  echo "monitor=$mon,preferred,auto,auto" >> "$config_file"
done

echo "monitor=,preferred,auto,auto" >> "$config_file"

mkdir -p "$(dirname "$env_file")"
echo "OMARCHY_PRIMARY_MONITOR=$primary_monitor" > "$env_file"

echo "Monitor configuration saved to $config_file"
echo "Primary set in $env_file"
