#!/bin/bash

# Detect monitors
if command -v hyprctl &> /dev/null; then
  # Try getting monitors from hyprctl if available
  monitors=$(hyprctl monitors all -j | jq -r '.[].name' | sort -u)
else
  # Fallback to sysfs (card0 usually)
  monitors=$(find /sys/class/drm -name "card*-*" | grep -v "\-TTM" | sed 's/.*card[0-9]*-\(.*\)/\1/' | sort -u)
fi

if [ -z "$monitors" ]; then
  echo "No monitors detected."
  exit 0
fi

echo "Detected monitors:"
echo "$monitors"

# Select monitors to enable
echo "Select monitors to ENABLE (Space to select, Enter to confirm):"
enabled_monitors=$(echo "$monitors" | gum choose --no-limit --header "Select monitors to ENABLE")

if [ -z "$enabled_monitors" ]; then
  echo "No monitors selected. Skipping monitor configuration."
  exit 0
fi

# Determine primary monitor
monitor_count=$(echo "$enabled_monitors" | wc -l)
primary_monitor=""

if [ "$monitor_count" -gt 1 ]; then
  echo "Select PRIMARY monitor:"
  primary_monitor=$(echo "$enabled_monitors" | gum choose --header "Select PRIMARY monitor")
else
  primary_monitor="$enabled_monitors"
fi

# Prepare to store configurations
declare -A monitor_configs

# Common resolutions
common_resolutions="preferred
highres
1920x1080@60
1920x1080@144
2560x1440@60
2560x1440@144
3840x2160@60
custom"

for mon in $enabled_monitors; do
  echo "Configuring $mon..."
  
  # === Resolution ===
  selected_res=""
  if command -v hyprctl &> /dev/null; then
    modes=$(hyprctl monitors all -j | jq -r --arg mon "$mon" '.[] | select(.name == $mon) | .availableModes[]' | head -n 20)
    if [ -n "$modes" ]; then
       options="preferred"$'\n'"highres"$'\n'"$modes"$'\n'"custom"
       selected_res=$(echo "$options" | gum choose --header "Select RESOLUTION for $mon")
    fi
  fi
  
  if [ -z "$selected_res" ]; then
     selected_res=$(echo "$common_resolutions" | gum choose --header "Select RESOLUTION for $mon")
  fi

  if [ "$selected_res" == "custom" ]; then
      selected_res=$(gum input --placeholder "e.g., 3840x2160@60" --header "Enter custom resolution (WxH@Hz)")
  fi

  # === Scale ===
  scale_options="1
1.33
1.5
2
custom"
  selected_scale=$(echo "$scale_options" | gum choose --header "Select SCALE for $mon")
  if [ "$selected_scale" == "custom" ]; then
      selected_scale=$(gum input --placeholder "e.g., 1.25" --header "Enter custom scale")
  fi

  # === Position ===
  # Auto is preferred to avoid overlaps
  pos_options="auto
custom"
  selected_pos=$(echo "$pos_options" | gum choose --header "Select POSITION for $mon")
  
  if [ "$selected_pos" == "custom" ]; then
      selected_pos=$(gum input --placeholder "e.g., 0x0 or 1920x0" --header "Enter position (XxY)")
  fi

  # === Orientation/Transform ===
  orientation_options="Normal (Landscape)
90 degrees (Portrait)
180 degrees (Inverted)
270 degrees (Portrait Flipped)"
  
  selected_ori=$(echo "$orientation_options" | gum choose --header "Select ORIENTATION for $mon")
  
  transform=0
  case "$selected_ori" in
    "Normal (Landscape)") transform=0 ;;
    "90 degrees (Portrait)") transform=1 ;;
    "180 degrees (Inverted)") transform=2 ;;
    "270 degrees (Portrait Flipped)") transform=3 ;;
  esac
  
  # Construct config line
  # Syntax: monitor=name,resolution,position,scale,transform,X
  monitor_configs["$mon"]="monitor=$mon,$selected_res,$selected_pos,$selected_scale,transform,$transform"
done


# Generate config content
config_file="$HOME/.config/hypr/monitors.conf"
vars_file="$HOME/.config/hypr/monitors-vars.conf"
env_file="$HOME/.config/environment.d/monitors.conf"

{
  echo "# Generated by Omarchy installer"
  echo "# See https://wiki.hyprland.org/Configuring/Monitors/"
  echo 
  echo "# Default scale for high-DPI (adjust as needed)"
  echo "env = GDK_SCALE,1"
  echo
} > "$config_file"

{
    echo "# Generated by Omarchy installer"
    echo "\$primary_monitor = $primary_monitor"
    
    # Define variables for other monitors (optional usage)
    # This is a basic index-based assignment from the detection order
    i=1
    for mon in $enabled_monitors; do
        if [ "$mon" != "$primary_monitor" ]; then
            echo "\$secondary_monitor_$i = $mon"
            ((i++))
        fi
    done
} > "$vars_file"

for mon in $enabled_monitors; do
  echo "${monitor_configs[$mon]}" >> "$config_file"
done

# Fallback for hotplugged monitors
echo "monitor=,preferred,auto,auto" >> "$config_file"

mkdir -p "$(dirname "$env_file")"
echo "OMARCHY_PRIMARY_MONITOR=$primary_monitor" > "$env_file"

echo "Monitor configuration saved to $config_file"
echo "Monitor variables saved to $vars_file"
echo "Primary set in $env_file: $primary_monitor"
